spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/loan_db
    username: postgres
    password: 050600

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    baseline-on-migrate: true